M48
; DRILL file {KiCad 7.0.1} date Tue Sep 12 17:25:18 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-12T17:25:18-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X99.025Y-61.592
X99.025Y-86.102
X145.975Y-61.592
X145.975Y-86.102
T0
M30
